package world;

import java.awt.Graphics2D;
import javax.imageio.ImageIO;
import main.GamePanel;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.BufferedReader;
import main.UtilityTool;
import java.awt.Color;


public class TileManager {
    
    GamePanel gp;
    public Tile[] tile;
    public int mapTileNum[][][];
    public int randomMap[] = {0, 1, 2, 3, 4};


    public TileManager(GamePanel gp, int randomMapIndex) {
        this.gp = gp;
        tile = new Tile[1200];
        mapTileNum = new int[gp.maxMap][gp.maxWorldCol][gp.maxWorldRow];

        getTileImage();
        loadMap("map"+ randomMapIndex +".txt", 0);
        loadMap("house.txt", 1);
        loadMap("forestRiver.txt", 2);
        loadMap("mountainLake.txt", 3);
        loadMap("ocean.txt", 4);
        loadMap("store.txt", 5);
        loadMap("mayorTadiHouse.txt", 6);
        loadMap("carolineHouse.txt", 7);
        loadMap("perryHouse.txt", 8);
        loadMap("dascoHouse.txt", 9);
        loadMap("abigailHouse.txt", 10);
        loadMap("easterEgg.txt", 11);
    }

    public void getTileImage() {
        setup (0, "/summer/0-Grass", false);
        setup (1, "/summer/1-Road", false);
        setup (2, "/summer/2-Grass_Road_Top_Left", false);
        setup (3, "/summer/3-Grass_Road_Top", false);
        setup (4, "/summer/4-Grass_Road_Top_Right", false);
        setup (5, "/summer/5-Grass_Road_Right", false);
        setup (6, "/summer/6-Grass_Road_Bottom_Right", false);
        setup (7, "/summer/7-Grass_Road_Bottom", false);
        setup (8, "/summer/8-Grass_Road_Bottom_Left", false);
        setup (9, "/summer/9-Grass_Road_Left", false);
        setup (10, "/house/House_Tiles_1", false);
        setup (11, "/house/House_Tiles_2", false);
        setup (12, "/house/House_Tiles_3", false);
        setup (13, "/house/House_Tiles_4", false);
        setup (14, "/house/House_Tiles_5", false);
        setup (15, "/house/House_Tiles_6", false);
        setup (16, "/house/House_Tiles_7", false);
        setup (17, "/house/House_Tiles_8", false);
        setup (18, "/house/House_Tiles_9", false);
        setup (19, "/house/House_Tiles_10", false);
        setup (20, "/house/House_Tiles_11", false);
        setup (21, "/house/House_Tiles_12", false);
        setup (22, "/house/House_Tiles_13", false);
        setup (23, "/house/House_Tiles_14", false);
        setup (24, "/house/House_Tiles_15", false);
        setup (25, "/house/House_Tiles_16", false);
        setup (26, "/house/Black", true);
        setup (27, "/summer/Soil", false);
        setup (28, "/summer/Grass_Road_Corner_UR", false);
        setup (29, "/summer/Grass_Road_Corner_BR", false);
        setup (30, "/summer/Grass_Road_Corner_BL", false);
        setup (31, "/forestRiver/ForestRiver_1", true);
        setup (32, "/forestRiver/ForestRiver_2", true);
        setup (33, "/forestRiver/ForestRiver_3", true);
        setup (34, "/forestRiver/ForestRiver_4", true);
        setup (35, "/forestRiver/ForestRiver_5", false);
        setup (36, "/forestRiver/ForestRiver_6", false);
        setup (37, "/forestRiver/ForestRiver_7", true);
        setup (38, "/forestRiver/ForestRiver_8", true);
        setup (39, "/forestRiver/ForestRiver_9", true);
        setup (40, "/forestRiver/ForestRiver_10", true);
        setup (41, "/forestRiver/ForestRiver_11", false);
        setup (42, "/forestRiver/ForestRiver_12", false);
        setup (43, "/forestRiver/ForestRiver_13", true);
        setup (44, "/forestRiver/ForestRiver_14", true);
        setup (45, "/forestRiver/ForestRiver_15", true);
        setup (46, "/forestRiver/ForestRiver_16", true);
        setup (47, "/forestRiver/ForestRiver_17", false);
        setup (48, "/forestRiver/ForestRiver_18", false);
        setup (49, "/forestRiver/ForestRiver_19", true);
        setup (50, "/forestRiver/ForestRiver_20", true);
        setup (51, "/forestRiver/ForestRiver_21", true);
        setup (52, "/forestRiver/ForestRiver_22", true);
        setup (53, "/forestRiver/ForestRiver_23", false);
        setup (54, "/forestRiver/ForestRiver_24", false);
        setup (55, "/forestRiver/ForestRiver_25", true);
        setup (56, "/forestRiver/ForestRiver_26", true);
        setup (57, "/forestRiver/ForestRiver_27", true);
        setup (58, "/forestRiver/ForestRiver_28", true);
        setup (59, "/forestRiver/ForestRiver_29", false);
        setup (60, "/forestRiver/ForestRiver_30", false);
        setup (61, "/forestRiver/ForestRiver_31", true);
        setup (62, "/forestRiver/ForestRiver_32", true);
        setup (63, "/forestRiver/ForestRiver_33", true);
        setup (64, "/forestRiver/ForestRiver_34", true);
        setup (65, "/forestRiver/ForestRiver_35", false);
        setup (66, "/forestRiver/ForestRiver_36", false);
        setup (67, "/house/house_1", true);
        setup (68, "/house/house_2", true);
        setup (69, "/house/house_3", true);
        setup (70, "/house/house_4", true);
        setup (71, "/house/house_5", true);
        setup (72, "/house/house_6", true);
        setup (73, "/house/house_7", true);
        setup (74, "/house/house_8", true);
        setup (75, "/house/house_9", true);
        setup (76, "/house/house_10", true);
        setup (77, "/house/house_11", true);
        setup (78, "/house/house_12", true);
        setup (79, "/house/house_13", true);
        setup (80, "/house/house_14", true);
        setup (81, "/house/house_15", true);
        setup (82, "/house/house_16", true);
        setup (83, "/house/house_17", true);
        setup (84, "/house/house_18", true);
        setup (85, "/house/house_19", true);
        setup (86, "/house/house_20", true);
        setup (87, "/house/house_21", true);
        setup (88, "/house/house_22", true);
        setup (89, "/house/house_23", true);
        setup (90, "/house/house_24", true);
        setup (91, "/house/house_25", true);
        setup (92, "/house/house_26", true);
        setup (93, "/house/house_27", true);
        setup (94, "/house/house_28", true);
        setup (95, "/house/house_29", true);
        setup (96, "/house/house_30", true);
        setup (97, "/house/house_31", true);
        setup (98, "/house/house_32", true);
        setup (99, "/house/house_33", true);
        setup (100, "/house/house_34", true);
        setup (101, "/house/house_35", true);
        setup (102, "/house/house_36", true);
        setup (103, "/house/house_37", true);
        setup (104, "/house/house_38", true);
        setup (105, "/house/house_39", true);
        setup (106, "/house/house_40", true);
        setup (107, "/house/house_41", true);
        setup (108, "/house/house_42", true);
        setup (109, "/house/house_43", true);
        setup (110, "/house/house_44", true);
        setup (111, "/house/house_45", true);
        setup (112, "/house/house_46", true);
        setup (113, "/house/house_47", true);
        setup (114, "/house/house_48", true);
        setup (115, "/house/house_49", true);
        setup (116, "/house/house_50", true);
        setup (117, "/house/house_51", true);
        setup (118, "/house/house_52", true);
        setup (119, "/house/house_53", true);
        setup (120, "/house/house_54", true);
        setup (121, "/house/house_55", true);
        setup (122, "/house/house_56", true);
        setup (123, "/house/house_57", true);
        setup (124, "/house/house_58", true);
        setup (125, "/house/house_59", true);
        setup (126, "/house/house_60", true);
        setup (127, "/house/house_61", true);
        setup (128, "/house/house_62", true);
        setup (129, "/house/house_63", true);
        setup (130, "/house/house_64", true);
        setup (131, "/house/house_65", true);
        setup (132, "/house/house_66", true);
        setup (133, "/house/house_67", true);
        setup (134, "/house/house_68", true);
        setup (135, "/house/house_69", true);
        setup (136, "/house/house_70", true);
        setup (137, "/house/house_71", true);
        setup (138, "/house/house_72", true);
        setup (139, "/house/house_73", true);
        setup (140, "/house/house_74", true);
        setup (141, "/house/house_75", true);
        setup (142, "/house/house_76", true);
        setup (143, "/house/house_77", false);
        setup (144, "/house/house_78", true);
        setup (145, "/house/house_79", true);
        setup (146, "/house/house_80", true);
        setup (147, "/house/house_81", true);
        setup (148, "/house/house_82", true);
        setup (149, "/house/house_83", false);
        setup (150, "/house/house_84", false);
        setup (151, "/house/house_85", false);
        setup (152, "/house/house_86", true);
        setup (153, "/house/house_87", false);
        setup (154, "/house/house_88", false);
        setup (155, "/house/house_89", true);
        setup (156, "/house/house_90", true);
        setup (157, "/house/house_91", true);
        setup (158, "/house/house_92", true);
        setup (159, "/house/house_93", true);
        setup (160, "/house/house_94", true);
        setup (161, "/house/house_95", true);
        setup (162, "/house/house_96", true);
        setup (163, "/house/house_97", true);
        setup (164, "/house/house_98", true);
        setup (165, "/house/house_99", false);
        setup (166, "/house/house_100", false);
        setup (167, "/house/house_101", false);
        setup (168, "/house/house_102", true);
        setup (169, "/house/house_103", true);
        setup (170, "/house/house_104", true);
        setup (171, "/house/house_105", false);
        setup (172, "/house/house_106", false);
        setup (173, "/house/house_107", false);
        setup (174, "/house/house_108", false);
        setup (175, "/house/house_109", false);
        setup (176, "/house/house_110", false);
        setup (177, "/house/house_111", false);
        setup (178, "/house/house_112", false);
        setup (179, "/house/house_113", false);
        setup (180, "/house/house_114", false);
        setup (181, "/house/house_115", false);
        setup (182, "/house/house_116", false);
        setup (183, "/house/house_117", false);
        setup (184, "/house/house_118", false);
        setup (185, "/house/house_119", true);
        setup (186, "/house/house_120", true);
        setup (187, "/house/house_121", true);
        setup (188, "/house/house_122", true);
        setup (189, "/house/house_123", false);
        setup (190, "/house/house_124", false);
        setup (191, "/house/house_125", false);
        setup (192, "/house/house_126", true);
        setup (193, "/house/house_127", true);
        setup (194, "/house/house_128", true);
        setup (195, "/house/house_129", true);
        setup (196, "/house/house_130", false);
        setup (197, "/house/house_131", false);
        setup (198, "/house/house_132", false);
        setup (199, "/house/house_133", false);
        setup (200, "/house/house_134", false);
        setup (201, "/house/house_135", false);
        setup (202, "/house/house_136", false);
        setup (203, "/house/house_137", false);
        setup (204, "/house/house_138", false);
        setup (205, "/house/house_139", false);
        setup (206, "/house/house_140", false);
        setup (207, "/house/house_141", false);
        setup (208, "/house/house_142", false);
        setup (209, "/house/house_143", false);
        setup (210, "/house/house_144", false);
        setup (211, "/house/house_145", false);
        setup (212, "/house/house_146", false);
        setup (213, "/house/house_147", false);
        setup (214, "/house/house_148", false);
        setup (215, "/house/house_149", false);
        setup (216, "/house/house_150", false);
        setup (217, "/house/house_151", false);
        setup (218, "/house/house_152", false);
        setup (219, "/house/house_153", false);
        setup (220, "/house/house_154", false);
        setup (221, "/house/house_155", false);
        setup (222, "/house/house_156", false);
        setup (223, "/house/house_157", false);
        setup (224, "/house/house_158", false);
        setup (225, "/house/house_159", false);
        setup (226, "/house/house_160", false);
        setup (227, "/house/house_161", false);
        setup (228, "/house/house_162", false);
        setup (229, "/house/house_163", false);
        setup (230, "/house/house_164", false);
        setup (231, "/house/house_165", false);
        setup (232, "/house/house_166", false);
        setup (233, "/house/house_167", false);
        setup (234, "/house/house_168", true);
        setup (235, "/house/house_169", true);
        setup (236, "/house/house_170", false);
        setup (237, "/house/house_171", false);
        setup (238, "/house/house_172", false);
        setup (239, "/house/house_173", false);
        setup (240, "/house/house_174", false);
        setup (241, "/house/house_175", false);
        setup (242, "/house/house_176", false);
        setup (243, "/house/house_177", false);
        setup (244, "/house/house_178", false);
        setup (245, "/house/house_179", false);
        setup (246, "/house/house_180", false);
        setup (247, "/house/house_181", false);
        setup (248, "/house/house_182", false);
        setup (249, "/house/house_183", false);
        setup (250, "/house/house_184", false);
        setup (251, "/house/house_185", false);
        setup (252, "/house/house_186", false);
        setup (253, "/house/house_187", false);
        setup (254, "/house/house_188", false);
        setup (255, "/house/house_189", false);
        setup (256, "/house/house_190", false);
        setup (257, "/house/house_191", false);
        setup (258, "/house/house_192", true);
        setup (259, "/house/house_193", true);
        setup (260, "/house/house_194", false);
        setup (261, "/house/house_195", false);
        setup (262, "/house/house_196", false);
        setup (263, "/house/house_197", false);
        setup (264, "/house/house_198", false);
        setup (265, "/house/house_199", false);
        setup (266, "/house/house_200", false);
        setup (267, "/house/house_201", false);
        setup (268, "/house/house_202", false);
        setup (269, "/house/house_203", false);
        setup (270, "/house/house_204", false);
        setup (271, "/house/house_205", false);
        setup (272, "/house/house_206", false);
        setup (273, "/house/house_207", false);
        setup (274, "/house/house_208", false);
        setup (275, "/house/house_209", false);
        setup (276, "/house/house_210", false);
        setup (277, "/house/house_211", false);
        setup (278, "/house/house_212", false);
        setup (279, "/house/house_213", false);
        setup (280, "/house/house_214", false);
        setup (281, "/house/house_215", false);
        setup (282, "/house/house_216", true);
        setup (283, "/house/house_217", true);
        setup (284, "/house/house_218", true);
        setup (285, "/house/house_219", true);
        setup (286, "/house/house_220", true);
        setup (287, "/house/house_221", true);
        setup (288, "/house/house_222", true);
        setup (289, "/house/house_223", true);
        setup (290, "/house/house_224", false);
        setup (291, "/house/house_225", false);
        setup (292, "/house/house_226", false);
        setup (293, "/house/house_227", false);
        setup (294, "/house/house_228", false);
        setup (295, "/house/house_229", false);
        setup (296, "/house/house_230", false);
        setup (297, "/house/house_231", false);
        setup (298, "/house/house_232", false);
        setup (299, "/house/house_233", false);
        setup (300, "/house/house_234", false);
        setup (301, "/house/house_235", false);
        setup (302, "/house/house_236", false);
        setup (303, "/house/house_237", false);
        setup (304, "/house/house_238", false);
        setup (305, "/house/house_239", false);
        setup (306, "/house/house_240", true);
        setup (307, "/house/house_241", true);
        setup (308, "/house/house_242", true);
        setup (309, "/house/house_243", true);
        setup (310, "/house/house_244", true);
        setup (311, "/house/house_245", true);
        setup (312, "/house/house_246", true);
        setup (313, "/house/house_247", true);
        setup (314, "/house/house_248", false);
        setup (315, "/house/house_249", false);
        setup (316, "/house/house_250", false);
        setup (317, "/house/house_251", false);
        setup (318, "/house/house_252", false);
        setup (319, "/house/house_253", false);
        setup (320, "/house/house_254", false);
        setup (321, "/house/house_255", false);
        setup (322, "/house/house_256", false);
        setup (323, "/house/house_257", false);
        setup (324, "/house/house_258", false);
        setup (325, "/house/house_259", false);
        setup (326, "/house/house_260", false);
        setup (327, "/house/house_261", false);
        setup (328, "/house/house_262", false);
        setup (329, "/house/house_263", false);
        setup (330, "/house/house_264", true);
        setup (331, "/house/house_265", true);
        setup (332, "/house/house_266", true);
        setup (333, "/house/house_267", true);
        setup (334, "/house/house_268", true);
        setup (335, "/house/house_269", true);
        setup (336, "/house/house_270", true);
        setup (337, "/house/house_271", true);
        setup (338, "/house/house_272", false);
        setup (339, "/house/house_273", false);
        setup (340, "/house/house_274", false);
        setup (341, "/house/house_275", false);
        setup (342, "/house/house_276", false);
        setup (343, "/house/house_277", false);
        setup (344, "/house/house_278", false);
        setup (345, "/house/house_279", false);
        setup (346, "/house/house_280", false);
        setup (347, "/house/house_281", false);
        setup (348, "/house/house_282", false);
        setup (349, "/house/house_283", true);
        setup (350, "/house/house_284", false);
        setup (351, "/house/house_285", false);
        setup (352, "/house/house_286", false);
        setup (353, "/house/house_287", false);
        setup (354, "/house/house_288", true);
        setup (355, "/house/house_289", true);
        setup (356, "/house/house_290", true);
        setup (357, "/house/house_291", true);
        setup (358, "/house/house_292", true);
        setup (359, "/house/house_293", true);
        setup (360, "/house/house_294", true);
        setup (361, "/house/house_295", true);
        setup (362, "/house/house_296", false);
        setup (363, "/house/house_297", false);
        setup (364, "/house/house_298", false);
        setup (365, "/house/house_299", false);
        setup (366, "/house/house_300", false);
        setup (367, "/house/house_301", false);
        setup (368, "/house/house_302", false);
        setup (369, "/house/house_303", false);
        setup (370, "/house/house_304", false);
        setup (371, "/house/house_305", false);
        setup (372, "/house/house_306", false);
        setup (373, "/house/house_307", false);
        setup (374, "/house/house_308", false);
        setup (375, "/house/house_309", false);
        setup (376, "/house/house_310", false);
        setup (377, "/house/house_311", false);
        setup (378, "/house/house_312", true);
        setup (379, "/house/house_313", true);
        setup (380, "/house/house_314", false);
        setup (381, "/house/house_315", false);
        setup (382, "/house/house_316", false);
        setup (383, "/house/house_317", false);
        setup (384, "/house/house_318", false);
        setup (385, "/house/house_319", false);
        setup (386, "/house/house_320", false);
        setup (387, "/house/house_321", false);
        setup (388, "/house/house_322", false);
        setup (389, "/house/house_323", false);
        setup (390, "/house/house_324", false);
        setup (391, "/house/house_325", false);
        setup (392, "/house/house_326", false);
        setup (393, "/house/house_327", false);
        setup (394, "/house/house_328", false);
        setup (395, "/house/house_329", false);
        setup (396, "/house/house_330", false);
        setup (397, "/house/house_331", false);
        setup (398, "/house/house_332", false);
        setup (399, "/house/house_333", false);
        setup (400, "/house/house_334", false);
        setup (401, "/house/house_335", false);
        setup (402, "/house/house_336", true);
        setup (403, "/house/house_337", true);
        setup (404, "/house/house_338", false);
        setup (405, "/house/house_339", false);
        setup (406, "/house/house_340", false);
        setup (407, "/house/house_341", false);
        setup (408, "/house/house_342", false);
        setup (409, "/house/house_343", false);
        setup (410, "/house/house_344", false);
        setup (411, "/house/house_345", false);
        setup (412, "/house/house_346", false);
        setup (413, "/house/house_347", false);
        setup (414, "/house/house_348", false);
        setup (415, "/house/house_349", false);
        setup (416, "/house/house_350", false);
        setup (417, "/house/house_351", false);
        setup (418, "/house/house_352", false);
        setup (419, "/house/house_353", false);
        setup (420, "/house/house_354", false);
        setup (421, "/house/house_355", false);
        setup (422, "/house/house_356", false);
        setup (423, "/house/house_357", false);
        setup (424, "/house/house_358", false);
        setup (425, "/house/house_359", false);
        setup (426, "/house/house_360", true);
        setup (427, "/house/house_361", true);
        setup (428, "/house/house_362", false);
        setup (429, "/house/house_363", false);
        setup (430, "/house/house_364", false);
        setup (431, "/house/house_365", false);
        setup (432, "/house/house_366", false);
        setup (433, "/house/house_367", false);
        setup (434, "/house/house_368", false);
        setup (435, "/house/house_369", false);
        setup (436, "/house/house_370", false);
        setup (437, "/house/house_371", false);
        setup (438, "/house/house_372", false);
        setup (439, "/house/house_373", false);
        setup (440, "/house/house_374", false);
        setup (441, "/house/house_375", false);
        setup (442, "/house/house_376", false);
        setup (443, "/house/house_377", false);
        setup (444, "/house/house_378", false);
        setup (445, "/house/house_379", true);
        setup (446, "/house/house_380", false);
        setup (447, "/house/house_381", false);
        setup (448, "/house/house_382", false);
        setup (449, "/house/house_383", false);
        setup (450, "/house/house_384", true);
        setup (451, "/house/house_385", true);
        setup (452, "/house/house_386", false);
        setup (453, "/house/house_387", false);
        setup (454, "/house/house_388", false);
        setup (455, "/house/house_389", false);
        setup (456, "/house/house_390", false);
        setup (457, "/house/house_391", false);
        setup (458, "/house/house_392", false);
        setup (459, "/house/house_393", false);
        setup (460, "/house/house_394", false);
        setup (461, "/house/house_395", false);
        setup (462, "/house/house_396", false);
        setup (463, "/house/house_397", false);
        setup (464, "/house/house_398", false);
        setup (465, "/house/house_399", false);
        setup (466, "/house/house_400", false);
        setup (467, "/house/house_401", false);
        setup (468, "/house/house_402", false);
        setup (469, "/house/house_403", false);
        setup (470, "/house/house_404", false);
        setup (471, "/house/house_405", false);
        setup (472, "/house/house_406", false);
        setup (473, "/house/house_407", false);
        setup (474, "/house/house_408", true);
        setup (475, "/house/house_409", true);
        setup (476, "/house/house_410", false);
        setup (477, "/house/house_411", false);
        setup (478, "/house/house_412", false);
        setup (479, "/house/house_413", false);
        setup (480, "/house/house_414", false);
        setup (481, "/house/house_415", false);
        setup (482, "/house/house_416", false);
        setup (483, "/house/house_417", false);
        setup (484, "/house/house_418", false);
        setup (485, "/house/house_419", false);
        setup (486, "/house/house_420", false);
        setup (487, "/house/house_421", false);
        setup (488, "/house/house_422", false);
        setup (489, "/house/house_423", false);
        setup (490, "/house/house_424", false);
        setup (491, "/house/house_425", false);
        setup (492, "/house/house_426", false);
        setup (493, "/house/house_427", false);
        setup (494, "/house/house_428", false);
        setup (495, "/house/house_429", false);
        setup (496, "/house/house_430", false);
        setup (497, "/house/house_431", false);
        setup (498, "/house/house_432", true);
        setup (499, "/house/house_433", true);
        setup (500, "/house/house_434", false);
        setup (501, "/house/house_435", false);
        setup (502, "/house/house_436", false);
        setup (503, "/house/house_437", true);
        setup (504, "/house/house_438", true);
        setup (505, "/house/house_439", false);
        setup (506, "/house/house_440", false);
        setup (507, "/house/house_441", false);
        setup (508, "/house/house_442", false);
        setup (509, "/house/house_443", false);
        setup (510, "/house/house_444", false);
        setup (511, "/house/house_445", false);
        setup (512, "/house/house_446", false);
        setup (513, "/house/house_447", false);
        setup (514, "/house/house_448", false);
        setup (515, "/house/house_449", false);
        setup (516, "/house/house_450", false);
        setup (517, "/house/house_451", false);
        setup (518, "/house/house_452", false);
        setup (519, "/house/house_453", false);
        setup (520, "/house/house_454", false);
        setup (521, "/house/house_455", false);
        setup (522, "/house/house_456", true);
        setup (523, "/house/house_457", true);
        setup (524, "/house/house_458", false);
        setup (525, "/house/house_459", false);
        setup (526, "/house/house_460", false);
        setup (527, "/house/house_461", true);
        setup (528, "/house/house_462", true);
        setup (529, "/house/house_463", false);
        setup (530, "/house/house_464", false);
        setup (531, "/house/house_465", false);
        setup (532, "/house/house_466", false);
        setup (533, "/house/house_467", false);
        setup (534, "/house/house_468", false);
        setup (535, "/house/house_469", false);
        setup (536, "/house/house_470", false);
        setup (537, "/house/house_471", false);
        setup (538, "/house/house_472", false);
        setup (539, "/house/house_473", false);
        setup (540, "/house/house_474", false);
        setup (541, "/house/house_475", false);
        setup (542, "/house/house_476", false);
        setup (543, "/house/house_477", false);
        setup (544, "/house/house_478", false);
        setup (545, "/house/house_479", false);
        setup (546, "/house/house_480", true);
        setup (547, "/house/house_481", true);
        setup (548, "/house/house_482", false);
        setup (549, "/house/house_483", false);
        setup (550, "/house/house_484", false);
        setup (551, "/house/house_485", false);
        setup (552, "/house/house_486", false);
        setup (553, "/house/house_487", false);
        setup (554, "/house/house_488", false);
        setup (555, "/house/house_489", false);
        setup (556, "/house/house_490", false);
        setup (557, "/house/house_491", false);
        setup (558, "/house/house_492", false);
        setup (559, "/house/house_493", false);
        setup (560, "/house/house_494", false);
        setup (561, "/house/house_495", false);
        setup (562, "/house/house_496", false);
        setup (563, "/house/house_497", false);
        setup (564, "/house/house_498", false);
        setup (565, "/house/house_499", false);
        setup (566, "/house/house_500", false);
        setup (567, "/house/house_501", false);
        setup (568, "/house/house_502", false);
        setup (569, "/house/house_503", false);
        setup (570, "/house/house_504", true);
        setup (571, "/house/house_505", true);
        setup (572, "/house/house_506", false);
        setup (573, "/house/house_507", false);
        setup (574, "/house/house_508", false);
        setup (575, "/house/house_509", false);
        setup (576, "/house/house_510", false);
        setup (577, "/house/house_511", false);
        setup (578, "/house/house_512", false);
        setup (579, "/house/house_513", false);
        setup (580, "/house/house_514", false);
        setup (581, "/house/house_515", false);
        setup (582, "/house/house_516", false);
        setup (583, "/house/house_517", false);
        setup (584, "/house/house_518", false);
        setup (585, "/house/house_519", false);
        setup (586, "/house/house_520", false);
        setup (587, "/house/house_521", false);
        setup (588, "/house/house_522", false);
        setup (589, "/house/house_523", false);
        setup (590, "/house/house_524", false);
        setup (591, "/house/house_525", false);
        setup (592, "/house/house_526", false);
        setup (593, "/house/house_527", false);
        setup (594, "/house/house_528", true);
        setup (595, "/house/house_529", true);
        setup (596, "/house/house_530", false);
        setup (597, "/house/house_531", false);
        setup (598, "/house/house_532", false);
        setup (599, "/house/house_533", false);
        setup (600, "/house/house_534", false);
        setup (601, "/house/house_535", false);
        setup (602, "/house/house_536", false);
        setup (603, "/house/house_537", false);
        setup (604, "/house/house_538", false);
        setup (605, "/house/house_539", false);
        setup (606, "/house/house_540", false);
        setup (607, "/house/house_541", false);
        setup (608, "/house/house_542", false);
        setup (609, "/house/house_543", false);
        setup (610, "/house/house_544", false);
        setup (611, "/house/house_545", false);
        setup (612, "/house/house_546", false);
        setup (613, "/house/house_547", false);
        setup (614, "/house/house_548", false);
        setup (615, "/house/house_549", false);
        setup (616, "/house/house_550", false);
        setup (617, "/house/house_551", false);
        setup (618, "/house/house_552", true);
        setup (619, "/house/house_553", true);
        setup (620, "/house/house_554", true);
        setup (621, "/house/house_555", true);
        setup (622, "/house/house_556", true);
        setup (623, "/house/house_557", true);
        setup (624, "/house/house_558", true);
        setup (625, "/house/house_559", true);
        setup (626, "/house/house_560", true);
        setup (627, "/house/house_561", true);
        setup (628, "/house/house_562", true);
        setup (629, "/house/house_563", false);
        setup (630, "/house/house_564", false);
        setup (631, "/house/house_565", false);
        setup (632, "/house/house_566", false);
        setup (633, "/house/house_567", true);
        setup (634, "/house/house_568", true);
        setup (635, "/house/house_569", true);
        setup (636, "/house/house_570", true);
        setup (637, "/house/house_571", true);
        setup (638, "/house/house_572", true);
        setup (639, "/house/house_573", true);
        setup (640, "/house/house_574", true);
        setup (641, "/house/house_575", true);
        setup (642, "/house/house_576", true);
        setup (643, "/mountainLake/mountainLake_1", false);
        setup (644, "/mountainLake/mountainLake_2", false);
        setup (645, "/mountainLake/mountainLake_3", false);
        setup (646, "/mountainLake/mountainLake_4", false);
        setup (647, "/mountainLake/mountainLake_5", false);
        setup (648, "/mountainLake/mountainLake_6", false);
        setup (649, "/mountainLake/mountainLake_7", false);
        setup (650, "/mountainLake/mountainLake_8", false);
        setup (651, "/mountainLake/mountainLake_9", false);
        setup (652, "/mountainLake/mountainLake_10", false);
        setup (653, "/mountainLake/mountainLake_11", false);
        setup (654, "/mountainLake/mountainLake_12", false);
        setup (655, "/mountainLake/mountainLake_13", true);
        setup (656, "/mountainLake/mountainLake_14", true);
        setup (657, "/mountainLake/mountainLake_15", false);
        setup (658, "/mountainLake/mountainLake_16", false);
        setup (659, "/mountainLake/mountainLake_17", false);
        setup (660, "/mountainLake/mountainLake_18", true);
        setup (661, "/mountainLake/mountainLake_19", true);
        setup (662, "/mountainLake/mountainLake_20", true);
        setup (663, "/mountainLake/mountainLake_21", false);
        setup (664, "/mountainLake/mountainLake_22", false);
        setup (665, "/mountainLake/mountainLake_23", false);
        setup (666, "/mountainLake/mountainLake_24", true);
        setup (667, "/mountainLake/mountainLake_25", true);
        setup (668, "/mountainLake/mountainLake_26", true);
        setup (669, "/mountainLake/mountainLake_27", true);
        setup (670, "/mountainLake/mountainLake_28", true);
        setup (671, "/mountainLake/mountainLake_29", true);
        setup (672, "/mountainLake/mountainLake_30", true);
        setup (673, "/mountainLake/mountainLake_31", true);
        setup (674, "/mountainLake/mountainLake_32", true);
        setup (675, "/mountainLake/mountainLake_33", true);
        setup (676, "/mountainLake/mountainLake_34", true);
        setup (677, "/mountainLake/mountainLake_35", true);
        setup (678, "/mountainLake/mountainLake_36", true);
        setup (679, "/ocean/Ocean_1", false);
        setup (680, "/ocean/Ocean_2", false);
        setup (681, "/ocean/Ocean_3", false);
        setup (682, "/ocean/Ocean_4", false);
        setup (683, "/ocean/Ocean_5", false);
        setup (684, "/ocean/Ocean_6", false);
        setup (685, "/ocean/Ocean_7", true);
        setup (686, "/ocean/Ocean_8", true);
        setup (687, "/ocean/Ocean_9", false);
        setup (688, "/ocean/Ocean_10", false);
        setup (689, "/ocean/Ocean_11", false);
        setup (690, "/ocean/Ocean_12", true);
        setup (691, "/ocean/Ocean_13", true);
        setup (692, "/ocean/Ocean_14", true);
        setup (693, "/ocean/Ocean_15", false);
        setup (694, "/ocean/Ocean_16", false);
        setup (695, "/ocean/Ocean_17", false);
        setup (696, "/ocean/Ocean_18", true);
        setup (697, "/ocean/Ocean_19", true);
        setup (698, "/ocean/Ocean_20", true);
        setup (699, "/ocean/Ocean_21", false);
        setup (700, "/ocean/Ocean_22", false);
        setup (701, "/ocean/Ocean_23", false);
        setup (702, "/ocean/Ocean_24", true);
        setup (703, "/ocean/Ocean_25", true);
        setup (704, "/ocean/Ocean_26", true);
        setup (705, "/ocean/Ocean_27", true);
        setup (706, "/ocean/Ocean_28", true);
        setup (707, "/ocean/Ocean_29", true);
        setup (708, "/ocean/Ocean_30", true);
        setup (709, "/ocean/Ocean_31", true);
        setup (710, "/ocean/Ocean_32", true);
        setup (711, "/ocean/Ocean_33", true);
        setup (712, "/ocean/Ocean_34", true);
        setup (713, "/ocean/Ocean_35", true);
        setup (714, "/ocean/Ocean_36", true);
        setup (715, "/store/Store_1", false);
        setup (716, "/store/Store_2", true);
        setup (717, "/store/Store_3", true);
        setup (718, "/store/Store_4", false);
        setup (719, "/store/Store_5", false);
        setup (720, "/store/Store_6", false);
        setup (721, "/store/Store_7", false);
        setup (722, "/store/Store_8", true);
        setup (723, "/store/Store_9", true);
        setup (724, "/store/Store_10", false);
        setup (725, "/store/Store_11", false);
        setup (726, "/store/Store_12", false);
        setup (727, "/store/Store_13", false);
        setup (728, "/store/Store_14", true);
        setup (729, "/store/Store_15", true);
        setup (730, "/store/Store_16", false);
        setup (731, "/store/Store_17", false);
        setup (732, "/store/Store_18", false);
        setup (733, "/store/Store_19", false);
        setup (734, "/store/Store_20", true);
        setup (735, "/store/Store_21", true);
        setup (736, "/store/Store_22", false);
        setup (737, "/store/Store_23", false);
        setup (738, "/store/Store_24", false);
        setup (739, "/store/Store_25", false);
        setup (740, "/store/Store_26", false);
        setup (741, "/store/Store_27", false);
        setup (742, "/store/Store_28", false);
        setup (743, "/store/Store_29", false);
        setup (744, "/store/Store_30", false);
        setup (745, "/store/Store_31", false);
        setup (746, "/store/Store_32", false);
        setup (747, "/store/Store_33", false);
        setup (748, "/store/Store_34", false);
        setup (749, "/store/Store_35", false);
        setup (750, "/store/Store_36", false);
        setup (751, "/carolineHouse/Caroline_1", true);
        setup (752, "/carolineHouse/Caroline_2", true);
        setup (753, "/carolineHouse/Caroline_3", true);
        setup (754, "/carolineHouse/Caroline_4", true);
        setup (755, "/carolineHouse/Caroline_5", true);
        setup (756, "/carolineHouse/Caroline_6", true);
        setup (757, "/carolineHouse/Caroline_7", true);
        setup (758, "/carolineHouse/Caroline_8", false);
        setup (759, "/carolineHouse/Caroline_9", false);
        setup (760, "/carolineHouse/Caroline_10", false);
        setup (761, "/carolineHouse/Caroline_11", false);
        setup (762, "/carolineHouse/Caroline_12", true);
        setup (763, "/carolineHouse/Caroline_13", true);
        setup (764, "/carolineHouse/Caroline_14", false);
        setup (765, "/carolineHouse/Caroline_15", false);
        setup (766, "/carolineHouse/Caroline_16", false);
        setup (767, "/carolineHouse/Caroline_17", false);
        setup (768, "/carolineHouse/Caroline_18", true);
        setup (769, "/carolineHouse/Caroline_19", true);
        setup (770, "/carolineHouse/Caroline_20", false);
        setup (771, "/carolineHouse/Caroline_21", false);
        setup (772, "/carolineHouse/Caroline_22", false);
        setup (773, "/carolineHouse/Caroline_23", false);
        setup (774, "/carolineHouse/Caroline_24", true);
        setup (775, "/carolineHouse/Caroline_25", false);
        setup (776, "/carolineHouse/Caroline_26", false);
        setup (777, "/carolineHouse/Caroline_27", false);
        setup (778, "/carolineHouse/Caroline_28", false);
        setup (779, "/carolineHouse/Caroline_29", false);
        setup (780, "/carolineHouse/Caroline_30", true);
        setup (781, "/carolineHouse/Caroline_31", false);
        setup (782, "/carolineHouse/Caroline_32", false);
        setup (783, "/carolineHouse/Caroline_33", false);
        setup (784, "/carolineHouse/Caroline_34", false);
        setup (785, "/carolineHouse/Caroline_35", false);
        setup (786, "/carolineHouse/Caroline_36", true);
        setup (787, "/perryHouse/Perry_1", true);
        setup (788, "/perryHouse/Perry_2", true);
        setup (789, "/perryHouse/Perry_3", true);
        setup (790, "/perryHouse/Perry_4", true);
        setup (791, "/perryHouse/Perry_5", true);
        setup (792, "/perryHouse/Perry_6", true);
        setup (793, "/perryHouse/Perry_7", true);
        setup (794, "/perryHouse/Perry_8", true);
        setup (795, "/perryHouse/Perry_9", true);
        setup (796, "/perryHouse/Perry_10", true);
        setup (797, "/perryHouse/Perry_11", true);
        setup (798, "/perryHouse/Perry_12", true);
        setup (799, "/perryHouse/Perry_13", false);
        setup (800, "/perryHouse/Perry_14", false);
        setup (801, "/perryHouse/Perry_15", false);
        setup (802, "/perryHouse/Perry_16", false);
        setup (803, "/perryHouse/Perry_17", false);
        setup (804, "/perryHouse/Perry_18", false);
        setup (805, "/perryHouse/Perry_19", true);
        setup (806, "/perryHouse/Perry_20", true);
        setup (807, "/perryHouse/Perry_21", false);
        setup (808, "/perryHouse/Perry_22", false);
        setup (809, "/perryHouse/Perry_23", false);
        setup (810, "/perryHouse/Perry_24", false);
        setup (811, "/perryHouse/Perry_25", true);
        setup (812, "/perryHouse/Perry_26", true);
        setup (813, "/perryHouse/Perry_27", false);
        setup (814, "/perryHouse/Perry_28", false);
        setup (815, "/perryHouse/Perry_29", false);
        setup (816, "/perryHouse/Perry_30", false);
        setup (817, "/perryHouse/Perry_31", true);
        setup (818, "/perryHouse/Perry_32", true);
        setup (819, "/perryHouse/Perry_33", false);
        setup (820, "/perryHouse/Perry_34", false);
        setup (821, "/perryHouse/Perry_35", false);
        setup (822, "/perryHouse/Perry_36", false);
        setup (823, "/abigailHouse/Abigail_1", true);
        setup (824, "/abigailHouse/Abigail_2", false);
        setup (825, "/abigailHouse/Abigail_3", false);
        setup (826, "/abigailHouse/Abigail_4", true);
        setup (827, "/abigailHouse/Abigail_5", true);
        setup (828, "/abigailHouse/Abigail_6", true);
        setup (829, "/abigailHouse/Abigail_7", false);
        setup (830, "/abigailHouse/Abigail_8", false);
        setup (831, "/abigailHouse/Abigail_9", false);
        setup (832, "/abigailHouse/Abigail_10", false);
        setup (833, "/abigailHouse/Abigail_11", false);
        setup (834, "/abigailHouse/Abigail_12", false);
        setup (835, "/abigailHouse/Abigail_13", false);
        setup (836, "/abigailHouse/Abigail_14", false);
        setup (837, "/abigailHouse/Abigail_15", false);
        setup (838, "/abigailHouse/Abigail_16", false);
        setup (839, "/abigailHouse/Abigail_17", false);
        setup (840, "/abigailHouse/Abigail_18", true);
        setup (841, "/abigailHouse/Abigail_19", false);
        setup (842, "/abigailHouse/Abigail_20", false);
        setup (843, "/abigailHouse/Abigail_21", false);
        setup (844, "/abigailHouse/Abigail_22", false);
        setup (845, "/abigailHouse/Abigail_23", false);
        setup (846, "/abigailHouse/Abigail_24", false);
        setup (847, "/abigailHouse/Abigail_25", false);
        setup (848, "/abigailHouse/Abigail_26", false);
        setup (849, "/abigailHouse/Abigail_27", false);
        setup (850, "/abigailHouse/Abigail_28", false);
        setup (851, "/abigailHouse/Abigail_29", false);
        setup (852, "/abigailHouse/Abigail_30", false);
        setup (853, "/abigailHouse/Abigail_31", false);
        setup (854, "/abigailHouse/Abigail_32", false);
        setup (855, "/abigailHouse/Abigail_33", false);
        setup (856, "/abigailHouse/Abigail_34", false);
        setup (857, "/abigailHouse/Abigail_35", false);
        setup (858, "/abigailHouse/Abigail_36", false);
        setup (859, "/mayorTadiHouse/MayorTadi_1", true);
        setup (860, "/mayorTadiHouse/MayorTadi_2", true);
        setup (861, "/mayorTadiHouse/MayorTadi_3", true);
        setup (862, "/mayorTadiHouse/MayorTadi_4", true);
        setup (863, "/mayorTadiHouse/MayorTadi_5", true);
        setup (864, "/mayorTadiHouse/MayorTadi_6", true);
        setup (865, "/mayorTadiHouse/MayorTadi_7", true);
        setup (866, "/mayorTadiHouse/MayorTadi_8", true);
        setup (867, "/mayorTadiHouse/MayorTadi_9", true);
        setup (868, "/mayorTadiHouse/MayorTadi_10", true);
        setup (869, "/mayorTadiHouse/MayorTadi_11", true);
        setup (870, "/mayorTadiHouse/MayorTadi_12", true);
        setup (871, "/mayorTadiHouse/MayorTadi_13", true);
        setup (872, "/mayorTadiHouse/MayorTadi_14", false);
        setup (873, "/mayorTadiHouse/MayorTadi_15", true);
        setup (874, "/mayorTadiHouse/MayorTadi_16", true);
        setup (875, "/mayorTadiHouse/MayorTadi_17", true);
        setup (876, "/mayorTadiHouse/MayorTadi_18", false);
        setup (877, "/mayorTadiHouse/MayorTadi_19", false);
        setup (878, "/mayorTadiHouse/MayorTadi_20", false);
        setup (879, "/mayorTadiHouse/MayorTadi_21", false);
        setup (880, "/mayorTadiHouse/MayorTadi_22", false);
        setup (881, "/mayorTadiHouse/MayorTadi_23", false);
        setup (882, "/mayorTadiHouse/MayorTadi_24", false);
        setup (883, "/mayorTadiHouse/MayorTadi_25", false);
        setup (884, "/mayorTadiHouse/MayorTadi_26", false);
        setup (885, "/mayorTadiHouse/MayorTadi_27", false);
        setup (886, "/mayorTadiHouse/MayorTadi_28", false);
        setup (887, "/mayorTadiHouse/MayorTadi_29", false);
        setup (888, "/mayorTadiHouse/MayorTadi_30", false);
        setup (889, "/mayorTadiHouse/MayorTadi_31", false);
        setup (890, "/mayorTadiHouse/MayorTadi_32", false);
        setup (891, "/mayorTadiHouse/MayorTadi_33", false);
        setup (892, "/mayorTadiHouse/MayorTadi_34", false);
        setup (893, "/mayorTadiHouse/MayorTadi_35", false);
        setup (894, "/mayorTadiHouse/MayorTadi_36", false);
        setup (895, "/dascoHouse/Dasco_1", true);
        setup (896, "/dascoHouse/Dasco_2", true);
        setup (897, "/dascoHouse/Dasco_3", true);
        setup (898, "/dascoHouse/Dasco_4", true);
        setup (899, "/dascoHouse/Dasco_5", true);
        setup (900, "/dascoHouse/Dasco_6", true);
        setup (901, "/dascoHouse/Dasco_7", false);
        setup (902, "/dascoHouse/Dasco_8", false);
        setup (903, "/dascoHouse/Dasco_9", false);
        setup (904, "/dascoHouse/Dasco_10", false);
        setup (905, "/dascoHouse/Dasco_11", false);
        setup (906, "/dascoHouse/Dasco_12", false);
        setup (907, "/dascoHouse/Dasco_13", false);
        setup (908, "/dascoHouse/Dasco_14", false);
        setup (909, "/dascoHouse/Dasco_15", false);
        setup (910, "/dascoHouse/Dasco_16", false);
        setup (911, "/dascoHouse/Dasco_17", false);
        setup (912, "/dascoHouse/Dasco_18", false);
        setup (913, "/dascoHouse/Dasco_19", false);
        setup (914, "/dascoHouse/Dasco_20", false);
        setup (915, "/dascoHouse/Dasco_21", false);
        setup (916, "/dascoHouse/Dasco_22", false);
        setup (917, "/dascoHouse/Dasco_23", false);
        setup (918, "/dascoHouse/Dasco_24", false);
        setup (919, "/dascoHouse/Dasco_25", false);
        setup (920, "/dascoHouse/Dasco_26", false);
        setup (921, "/dascoHouse/Dasco_27", false);
        setup (922, "/dascoHouse/Dasco_28", false);
        setup (923, "/dascoHouse/Dasco_29", false);
        setup (924, "/dascoHouse/Dasco_30", false);
        setup (925, "/dascoHouse/Dasco_31", false);
        setup (926, "/dascoHouse/Dasco_32", true);
        setup (927, "/dascoHouse/Dasco_33", true);
        setup (928, "/dascoHouse/Dasco_34", true);
        setup (929, "/dascoHouse/Dasco_35", true);
        setup (930, "/dascoHouse/Dasco_36", true);
        setup (931, "/summer/Grass_Road_Corner_UL", false);
        setup (932, "/winter/KiriAtas", false);
        setup (933, "/winter/Atas", false);
        setup (934, "/winter/KananAtas", false);
        setup (935, "/winter/Kanan", false);
        setup (936, "/winter/KananBawah", false);
        setup (937, "/winter/Bawah", false);
        setup (938, "/winter/KiriBawah", false);
        setup (939, "/winter/Kiri", false);
        setup (940, "/winter/UpperRight", false);
        setup (941, "/winter/BottomRight", false);
        setup (942, "/winter/BottomLeft", false);
        setup (943, "/winter/UpperLeft", false);
        setup (944, "/winter/Grass", false);
        setup (945, "/winter/Snow", false);
        setup (946, "/spring/Grass", false);
        setup (947, "/spring/Road", false);
        setup (948, "/spring/KiriAtas", false);
        setup (949, "/spring/Atas", false);
        setup (950, "/spring/KananAtas", false);
        setup (951, "/spring/Kanan", false);
        setup (952, "/spring/KananBawah", false);
        setup (953, "/spring/Bawah", false);
        setup (954, "/spring/KiriBawah", false);
        setup (955, "/spring/Kiri", false);
        setup (956, "/spring/UpperRight", false);
        setup (957, "/spring/BottomRight", false);
        setup (958, "/spring/BottomLeft", false);
        setup (959, "/spring/UpperLeft", false);
        setup (960, "/fall/Grass", false);
        setup (961, "/fall/Road", false);
        setup (962, "/fall/KiriAtas", false);
        setup (963, "/fall/Atas", false);
        setup (964, "/fall/KananAtas", false);
        setup (965, "/fall/Kanan", false);
        setup (966, "/fall/KananBawah", false);
        setup (967, "/fall/Bawah", false);
        setup (968, "/fall/KiriBawah", false);
        setup (969, "/fall/Kiri", false);
        setup (970, "/fall/UpperRight", false);
        setup (971, "/fall/BottomRight", false);
        setup (972, "/fall/BottomLeft", false);
        setup (973, "/fall/UpperLeft", false);
        setup (974, "/fall/Soil", false);
        setup (975, "/spring/Soil", false);
        setup (976, "/winter/Soil", false);
        setup (977, "/easterEgg/EasterEgg_1", false);
        setup (978, "/easterEgg/EasterEgg_2", false);
        setup (979, "/easterEgg/EasterEgg_3", false);
        setup (980, "/easterEgg/EasterEgg_4", false);
        setup (981, "/easterEgg/EasterEgg_5", false);
        setup (982, "/easterEgg/EasterEgg_6", false);
        setup (983, "/easterEgg/EasterEgg_7", false);
        setup (984, "/easterEgg/EasterEgg_8", false);
        setup (985, "/easterEgg/EasterEgg_9", false);
        setup (986, "/easterEgg/EasterEgg_10", false);
        setup (987, "/easterEgg/EasterEgg_11", false);
        setup (988, "/easterEgg/EasterEgg_12", false);
        setup (989, "/easterEgg/EasterEgg_13", false);
        setup (990, "/easterEgg/EasterEgg_14", false);
        setup (991, "/easterEgg/EasterEgg_15", false);
        setup (992, "/easterEgg/EasterEgg_16", false);
        setup (993, "/easterEgg/EasterEgg_17", false);
        setup (994, "/easterEgg/EasterEgg_18", false);
        setup (995, "/easterEgg/EasterEgg_19", false);
        setup (996, "/easterEgg/EasterEgg_20", false);
        setup (997, "/easterEgg/EasterEgg_21", false);
        setup (998, "/easterEgg/EasterEgg_22", false);
        setup (999, "/easterEgg/EasterEgg_23", false);
        setup (1000, "/easterEgg/EasterEgg_24", false);
        setup (1001, "/easterEgg/EasterEgg_25", false);
        setup (1002, "/easterEgg/EasterEgg_26", false);
        setup (1003, "/easterEgg/EasterEgg_27", false);
        setup (1004, "/easterEgg/EasterEgg_28", false);
        setup (1005, "/easterEgg/EasterEgg_29", false);
        setup (1006, "/easterEgg/EasterEgg_30", false);
        setup (1007, "/easterEgg/EasterEgg_31", true);
        setup (1008, "/easterEgg/EasterEgg_32", true);
        setup (1009, "/easterEgg/EasterEgg_33", false);
        setup (1010, "/easterEgg/EasterEgg_34", false);
        setup (1011, "/easterEgg/EasterEgg_35", true);
        setup (1012, "/easterEgg/EasterEgg_36", true);
    }

    public void setup(int index, String imagePath, boolean collision) {

        UtilityTool uTool = new UtilityTool();

        try {
            tile[index] = new Tile();
            tile[index].image = ImageIO.read(getClass().getResourceAsStream("/tiles/" + imagePath + ".png"));
            tile[index].image = uTool.scaleImage(tile[index].image, gp.tileSize, gp.tileSize);
            tile[index].collision = collision;
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loadMap(String filePath, int map) {
        try {
            InputStream is = getClass().getResourceAsStream("/maps/" + filePath);
            BufferedReader br = new BufferedReader(new InputStreamReader(is));

            int col = 0;
            int row = 0;

            while (col < gp.maxWorldCol && row < gp.maxWorldRow) {
                String line = br.readLine();

                while (col < gp.maxWorldCol) {
                    String numbers[] = line.split(" ");
                    int num = Integer.parseInt(numbers[col]);
                    mapTileNum[map][col][row] = num;
                    col++;
                }
                if (col == gp.maxWorldCol) {
                    col = 0;
                    row++;
                }
            }
            br.close();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }

    public int getEffectiveTileID(int baseTileID) {
        String currentSeasonName = "Summer";
        if (gp.farm != null && gp.farm.getSeason() != null) {
            currentSeasonName = gp.farm.getSeason().getCurrentSeason();
        }
        switch (baseTileID) {
            case 0:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 944;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 946;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 960;
                return 0;
            case 1:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 945;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 947;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 961;
                return 1;

            case 2:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 932;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 948;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 962;
                return 2;
            case 3:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 933;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 949;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 963;
                return 3;
            case 4:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 934;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 950;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 964;
                return 4;
            case 5:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 935;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 951;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 965;
                return 5;
            case 6:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 936;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 952;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 966;
                return 6;
            case 7:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 937;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 953;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 967;
                return 7;
            case 8:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 938;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 954;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 968;
                return 8;
            case 9:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 939;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 955;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 969;
                return 9;
            case 27:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 976;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 975;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 974;
                return 27;
            case 28:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 940;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 956;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 970;
                return 28;
            case 29:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 941;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 957;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 971;
                return 29;
            case 30:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 942;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 958;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 972;
                return 30;
            case 931:
                if ("Winter".equalsIgnoreCase(currentSeasonName)) return 943;
                else if ("Spring".equalsIgnoreCase(currentSeasonName)) return 959;
                else if ("Fall".equalsIgnoreCase(currentSeasonName)) return 973;
                return 931;

            default:
                return baseTileID;
        }
    }


    public void draw(Graphics2D g2) {
        
        int worldCol = 0;
        int worldRow = 0;

        while (worldCol < gp.maxWorldCol && worldRow < gp.maxWorldRow) {
            int baseTileNum = mapTileNum[gp.currentMap][worldCol][worldRow];

            int effectiveTileNum = getEffectiveTileID(baseTileNum);

            if (effectiveTileNum < 0 || effectiveTileNum >= tile.length || tile[effectiveTileNum] == null || tile[effectiveTileNum].image == null) {
                if (baseTileNum >= 0 && baseTileNum < tile.length && tile[baseTileNum] != null && tile[baseTileNum].image != null) {
                    effectiveTileNum = baseTileNum; 
                } else {
                    g2.setColor(Color.DARK_GRAY);
                    int screenXError = worldCol * gp.tileSize - gp.player.worldX + gp.player.screenX;
                    int screenYError = worldRow * gp.tileSize - gp.player.worldY + gp.player.screenY;
                    g2.fillRect(screenXError, screenYError, gp.tileSize, gp.tileSize);
                    
                    worldCol++;
                    if (worldCol == gp.maxWorldCol) {
                        worldCol = 0;
                        worldRow++;
                    }
                    continue; 
                }
            }

            int worldX = worldCol * gp.tileSize;
            int worldY = worldRow * gp.tileSize;
            int screenX = worldX - gp.player.worldX + gp.player.screenX;
            int screenY = worldY - gp.player.worldY + gp.player.screenY;

            int cameraLeftWorldX = gp.player.worldX - gp.player.screenX;
            int cameraTopWorldY = gp.player.worldY - gp.player.screenY;

            if (worldX + gp.tileSize > cameraLeftWorldX &&
                worldX < cameraLeftWorldX + gp.screenWidth &&
                worldY + gp.tileSize > cameraTopWorldY &&
                worldY < cameraTopWorldY + gp.screenHeight) {
                
                g2.drawImage(tile[effectiveTileNum].image, screenX, screenY, gp.tileSize, gp.tileSize, null);
            }

            worldCol++;
            
            if (worldCol == gp.maxWorldCol) {
                worldCol = 0;
                worldRow++;
            }
        }
    }
}
